.TH UC-CLI "1" "June 2016" "pop-cli 0.12"
.SH NAME
pop-cli \- a remote procedure call client for Pop Core. 
.SH SYNOPSIS
pop-cli [options] <command> [params] \- Send command to Pop Core. 
.TP
pop-cli [options] help \- Asks Pop Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the pop-cli program. pop-cli is an RPC client used to send commands to Pop Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBpopd\fP, \fBpop.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
